global:
  scrape_interval: 1m
  evaluation_interval: 1m

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["192.168.12.179:9093"]

rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["192.168.12.179:9090"]

  - job_name: "node_local"
    static_configs:
    - targets: ["192.168.12.179:9100"]

  - job_name: "node_wordpress"
    static_configs:
    - targets: ["192.168.12.168:9100"]

  - job_name: 'blackbox_dns_site'
    metrics_path: /probe
    params:
      module: [http_2xx]
    dns_sd_configs:
      - names:
          - cloud.cardio32.ru
        type: A
        port: 443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://192.168.12.168:443/ 
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.12.179:9115
      - source_labels: [__meta_dns_name]
        target_label: __param_hostname
      - source_labels: [__meta_dns_name]
        target_label: vhost
 